language: python
sudo: false

# If you need X11:
services:
    - xvfb

# This is for X11 too:
addons:
    apt:
      packages:
        - herbstluftwm
        - libxkbcommon-x11-0

env:
  global:
    # Doctr deploy key for <org>/<repo>
    - secure: "<docs build key>"
    # You only need to specify these if they are different from these values
    - REQUIREMENTS: requirements.txt
    - DEV_REQUIREMENTS: dev-requirements.txt
    - DOCS_REQUIREMENTS: docs-requirements.txt
    - DOCS_FOLDER: docs
    # Assign this variable if you want a version menu in your docs
    - DOCTR_VERSIONS_MENU: 1
    # Assign this variable to include folders that start with an underscore in
    # your gh-pages site. This is already done when using DOCTR_VERSIONS_MENU
    # so you don't need to set both.
    - NO_JEKYLL: 1
    # Assign this variable to specify options for the python linter
    - PYTHON_LINT_OPTIONS="source --verbose"

# Also for X11:
before_script:
  # Run the window manager
  - "herbstluftwm &"
  - sleep 1

stages:
  - test
  - name: deploy
    if: (branch = master OR tag IS present) AND type != pull_request

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-linter.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-tester.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/pypi-upload.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/doctr-upload.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-upload.yml
