version: ~> 1.0

language: python
os: linux
dist: xenial

stages:
  - build
  - test
  - name: deploy
    if: (branch = master OR tag IS present) AND type != pull_request

import:
  # Build stage
  - travis/shared_configs/twincat/setup.yml
  # Test stage
  - travis/shared_configs/twincat/docs-build.yml
  - travis/shared_configs/twincat/pragmalint.yml
  - travis/shared_configs/twincat/pre-commit.yml
  - travis/shared_configs/twincat/style.yml
  - travis/shared_configs/twincat/summary.yml
  # Deploy stage
  - travis/shared_configs/twincat/doctr-upload.yml
