version: ~> 1.0

jobs:
  include:
      - stage: build
        name: "Anaconda Build"
        workspaces:
          create:
            name: conda
            paths:
              - bld-dir
        install:
          - curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          - eval "$(./bin/micromamba shell hook --shell=bash)"
          - mkdir ~/micromamba
          - micromamba activate
          - micromamba config --set always_yes yes
          - micromamba config --set changeps1 no
          - micromamba config --set channel_priority strict
          - micromamba config --remove channels defaults
          - micromamba config --add channels pcds-tag
          - micromamba config --add channels conda-forge
          # Useful for debugging
          - micromamba info
          - micromamba config list
          - micromamba install boa

        script:
          - echo "Conda Recipe Folder':' ${CONDA_RECIPE_FOLDER}"
          - echo "DEBUG RECIPE:"
          - cat ${CONDA_RECIPE_FOLDER}/meta.yaml
          - conda mambabuild -q $CONDA_RECIPE_FOLDER --output-folder bld-dir --no-anaconda-upload
