jobs:
  include:
    - stage: deploy
      name: "Anaconda Upload"
      if: |
        type != pull_request AND \
        env(CONDA_UPLOAD_TOKEN_DEV) IS present AND \
        (branch = master OR \
        (branch = tag AND env(CONDA_UPLOAD_TOKEN_TAG) IS present))
      python: 3.7
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - source $HOME/miniconda/etc/profile.d/conda.sh
        - conda activate base
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
      install:
        - conda install python=$TRAVIS_PYTHON_VERSION conda-build=3.12.0
        - conda config --add channels pcds-tag
        - conda config --append channels conda-forge
        - conda config --remove channels defaults
        - conda build -q conda-recipe --python=$TRAVIS_PYTHON_VERSION --output-folder bld-dir
        - echo "Installing anaconda-client"
        - conda install anaconda-client
      script:
        - |
          if [[ $TRAVIS_BRANCH == $TRAVIS_TAG ]]; then
              echo "Uploading to pcds-tag channel"
              export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_TAG
              anaconda upload bld-dir/noarch/*.tar.bz2
          fi
        - echo "Uploading to pcds-dev channel"
        - export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_DEV
        - anaconda upload bld-dir/noarch/*.tar.bz2
