version: ~> 1.0

jobs:
  include:
    - stage: deploy
      name: "Anaconda Upload"
      workspaces:
        use: conda
      if: |
        type != pull_request AND \
        env(CONDA_UPLOAD_TOKEN_DEV) IS present AND \
        (branch = master OR \
        (branch = tag AND env(CONDA_UPLOAD_TOKEN_TAG) IS present))
      python: 3.7
      before_script:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda install anaconda-client

      script:
        - |
          if [[ $TRAVIS_BRANCH == $TRAVIS_TAG ]]; then
              echo "Uploading to pcds-tag channel"
              export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_TAG
              anaconda upload bld-dir/noarch/*.tar.bz2
          fi
        - echo "Uploading to pcds-dev channel"
        - export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_DEV
        - anaconda upload bld-dir/noarch/*.tar.bz2
