version: ~> 1.0

jobs:
  include:
      - stage: build
        name: "Anaconda Build"
        workspaces:
          create:
            name: conda
            paths:
              - bld-dir
        install:
          - curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj micromamba
          - ./micromamba shell init -s bash -p ~/conda
          - ./micromamba activate
          - mamba config --set always_yes yes
          - mamba config --set changeps1 no
          - mamba config --set channel_priority strict
          - mamba config --remove channels defaults
          - mamba config --add channels pcds-tag
          - mamba config --add channels conda-forge
          # Useful for debugging
          - mamba info -a
          - mamba config --show
          - mamba install boa

        script:
          - echo "Conda Recipe Folder':' ${CONDA_RECIPE_FOLDER}"
          - echo "DEBUG RECIPE:"
          - cat ${CONDA_RECIPE_FOLDER}/meta.yaml
          - conda mambabuild -q $CONDA_RECIPE_FOLDER --output-folder bld-dir --no-anaconda-upload
