jobs:
  include:
    - stage: deploy
      name: "Anaconda Upload"
      if: |
        type != pull_request AND \
        env(CONDA_UPLOAD_TOKEN_DEV) IS present AND \
        (branch = master OR \
        (branch = tag AND env(CONDA_UPLOAD_TOKEN_TAG) IS present))
      python: 3.7
      script:
        - |
          if [[ $TRAVIS_BRANCH == $TRAVIS_TAG ]]; then
              echo "Uploading to pcds-tag channel"
              export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_TAG
              anaconda upload bld-dir/noarch/*.tar.bz2
          fi
        - echo "Uploading to pcds-dev channel"
        - export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_DEV
        - anaconda upload bld-dir/noarch/*.tar.bz2

import:
  # Order is important here as this is parsed depth-first so it should be
  # the opposite of what makes sense.
  - travis/shared_configs/utils-conda-build.yml
  - travis/shared_configs/utils-conda-install-config.yml
