version: ~> 1.0

jobs:
  include:
      stage: build
      name: "Anaconda Build"
      python: 3.6
      workspaces:
        create:
          name: conda
          paths:
            - bld-dir

      script:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda install conda-build anaconda-client
        - conda update -q conda conda-build
        - conda config --remove channels defaults
        - conda config --add channels conda-forge
        # Useful for debugging
        - conda info -a

        - echo "Conda Recipe Folder':' ${CONDA_RECIPE_FOLDER}"
        - conda build -q $CONDA_RECIPE_FOLDER --python $TRAVIS_PYTHON_VERSION --output-folder bld-dir
