jobs:
  include:
    - stage: test
      env:
        - CONDA_PACKAGE: ""
        - CONDA_RECIPE_FOLDER: ""
      name: "Docs Build"
      before_script:
        - echo "Docs Req File':' ${DOCS_REQUIREMENTS:=docs-requirements.txt}"
        - echo "Docs Folder':' ${DOCS_FOLDER:=docs}"
        - |
          # Install docs requirements
          for req in ${DOCS_REQUIREMENTS};
          do
            if [[ ! -f "${req}" ]]; then
                echo "File not found: ${req}" 1>&2
                travis_terminate 1
            else
                pip install --upgrade --requirement "${req}"
            fi
          done
      script:
        - |
          # Create HTML documentation
          set -e
          pushd ${DOCS_FOLDER}
          make html
          popd
      after_script:
        - set +e

import:
  # Order is important here as this is parsed depth-first so it should be
  # the opposite of what makes sense.
  - source: travis/shared_configs/utils-conda-install-config.yml
    mode: deep_merge_prepend
  - source: travis/shared_configs/utils-conda-build.yml
    mode: deep_merge_prepend
  - source: travis/shared_configs/utils-conda-create.yml
    mode: deep_merge_prepend
