version: ~> 1.0

jobs:
  include:
    - stage: test
      name: "Docs Build"
      env:
        - PYTHON_VERSION: 3.9
      workspaces:
        create:
          name: docs
          paths:
            - docs/build/
        use: conda
      install: skip
      before_script:
        - curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj micromamba
        - ./micromamba shell init -s bash -p ~/conda
        - ./micromamba activate
        - mamba config --set always_yes yes
        - mamba config --set changeps1 no
        - mamba config --set channel_priority strict
        - mamba config --remove channels defaults
        - mamba config --add channels pcds-tag
        - mamba config --add channels conda-forge
        - mamba config --add channels "file://`pwd`/bld-dir"
        # Useful for debugging
        - mamba info -a
        - mamba config --show
        - echo "Conda Environment Name':' ${CONDA_ENV_NAME:=testenv}"
        # Manage conda environment
        - mamba create -n ${CONDA_ENV_NAME} python=$PYTHON_VERSION ${CONDA_PACKAGE} ${CONDA_EXTRAS}
        - ./micromamba activate ${CONDA_ENV_NAME}
        # Useful for debugging
        - mamba list

        - echo "Docs Req File':' ${DOCS_REQUIREMENTS:=docs-requirements.txt}"
        - echo "Docs Folder':' ${DOCS_FOLDER:=docs}"
        - |
          # Install docs requirements
          for req in ${DOCS_REQUIREMENTS};
          do
            if [[ ! -f "${req}" ]]; then
                echo "File not found: ${req}" 1>&2
                travis_terminate 1
            else
                pip install --requirement "${req}"
            fi
          done
      script:
        - |
          # Create HTML documentation
          set -e
          pushd ${DOCS_FOLDER}
          make html
          popd
      after_script:
        - set +e
