version: ~> 1.0

jobs:
  include:
    - stage: test
      name: "Docs Build"
      env:
        - PYTHON_VERSION: 3.9
      workspaces:
        create:
          name: docs
          paths:
            - docs/build/
        use: conda
      install: skip
      before_script:
        - curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
        - eval "$(./bin/micromamba shell hook --shell=bash)"
        - mkdir ~/micromamba
        - micromamba activate
        - micromamba config --set always_yes yes
        - micromamba config --set changeps1 no
        - micromamba config --set channel_priority strict
        - micromamba config --remove channels defaults
        - micromamba config --add channels pcds-tag
        - micromamba config --add channels conda-forge
        # Useful for debugging
        - micromamba info
        - micromamba config list
        - echo "Conda Environment Name':' ${CONDA_ENV_NAME:=testenv}"
        - echo "Conda Requirements':' ${CONDA_REQUIREMENTS:=dev-requirements.txt}"

        # Manage conda environment
        - micromamba create -n ${CONDA_ENV_NAME} python=$PYTHON_VERSION ${CONDA_PACKAGE} ${CONDA_EXTRAS} --file ${CONDA_REQUIREMENTS}
        - micromamba activate ${CONDA_ENV_NAME}
        # Useful for debugging
        - micromamba list

        - echo "Docs Req File':' ${DOCS_REQUIREMENTS:=docs-requirements.txt}"
        - echo "Docs Folder':' ${DOCS_FOLDER:=docs}"
        - |
          # Install docs requirements
          for req in ${DOCS_REQUIREMENTS};
          do
            if [[ ! -f "${req}" ]]; then
                echo "File not found: ${req}" 1>&2
                travis_terminate 1
            else
                pip install --requirement "${req}"
            fi
          done
      script:
        - |
          # Create HTML documentation
          set -e
          pushd ${DOCS_FOLDER}
          make html
          popd
      after_script:
        - set +e
