jobs:
  include:
    - stage: deploy
      name: "Docs Upload"
      env:
        - CONDA_PACKAGE: ""
        - CONDA_RECIPE_FOLDER: ""
      if: |
        type != pull_request AND \
        (branch = master OR tag IS present)
      install: skip
      before_script:
        - echo "Docs Req File':' ${DOCS_REQUIREMENTS:=docs-requirements.txt}"
        - echo "Docs Folder':' ${DOCS_FOLDER:=docs}"
        - |
          # Install docs requirements
          for req in ${DOCS_REQUIREMENTS};
          do
            if [[ ! -f "${req}" ]]; then
                echo "File not found: ${req}" 1>&2
                travis_terminate 1
            else
                pip install --upgrade --requirement "${req}"
            fi
          done
      script:
        - |
          # Create HTML documentation
          set -e
          pushd ${DOCS_FOLDER}
          make html
          popd
        - |
          if [[ ! -z "$DOCTR_VERSIONS_MENU" ]]; then
              DOCTR_VERSIONS_COMMAND='--command "doctr-versions-menu"'
          fi
        - DEPLOY_DIR="${TRAVIS_TAG:=master}"
      after_script:
        - echo "$ doctr deploy --build-tags $DEPLOY_DIR --deploy-branch-name
          gh-pages $DOCTR_VERSIONS_COMMAND"
        - doctr deploy --build-tags $DEPLOY_DIR --deploy-branch-name gh-pages
          $DOCTR_VERSIONS_COMMAND
        - set +e

import:
  - travis/shared_configs/utils-conda.yml
