jobs:
  include:
    - stage: deploy
      name: "Docs Upload"
      install:
        - echo "Docs Req File':' ${DOCS_REQUIREMENTS:=docs-requirements.txt}"
        - echo "Docs Folder':' ${DOCS_FOLDER:=docs}"
        - |
          # Install docs requirements
          if [[ ! -f "${DOCS_REQUIREMENTS}" ]]; then
              echo "File not found: ${DOCS_REQUIREMENTS}" 1>&2
              travis_terminate 1
          else
              pip install --upgrade --requirement "${DOCS_REQUIREMENTS}"
          fi
      before_script:
        - |
          # Create HTML documentation
          set -e
          pushd ${DOCS_FOLDER}
          make html
          popd
        - |
          if [[ ! -z "$NO_JEKYLL" ]]; then
              NO_JEKYLL_COMMAND='--command "touch .nojekyll; git add .nojekyll"'
          fi
        - |
          if [[ ! -z "$DOCTR_VERSIONS_MENU" ]]; then
              DOCTR_VERSIONS_COMMAND='--command "doctr-versions-menu"'
          fi
        - |
          if [[ -z "$TRAVIS_TAG" ]]; then
              DEPLOY_DIR=master;
          else
              DEPLOY_DIR="$TRAVIS_TAG";
          fi
      script:
        - echo "$ doctr deploy --build-tags $DEPLOY_DIR --deploy-branch-name
          gh-pages $NO_JEKYLL_COMMAND $DOCTR_VERSIONS_COMMAND"
        - doctr deploy --build-tags $DEPLOY_DIR --deploy-branch-name gh-pages
          $NO_JEKYLL_COMMAND $DOCTR_VERSIONS_COMMAND
      after_script:
        - set +e
