jobs:
  include:
    - stage: deploy
      name: "Docs Upload"
      python: 3.6
      workspaces:
        use: docs
      if: |
        type != pull_request AND \
        (branch = master OR tag IS present)
      install:
        pip install doctr doctr-versions-menu
      script:
        - |
          if [[ ! -z "$DOCTR_VERSIONS_MENU" ]]; then
              DOCTR_VERSIONS_COMMAND='--command "doctr-versions-menu"'
          fi
        - DEPLOY_DIR="${TRAVIS_TAG:=master}"
      after_script:
        - echo "$ doctr deploy --build-tags $DEPLOY_DIR --deploy-branch-name
          gh-pages $DOCTR_VERSIONS_COMMAND"
        - doctr deploy --build-tags $DEPLOY_DIR --deploy-branch-name gh-pages
          $DOCTR_VERSIONS_COMMAND
        - set +e
