version: ~> 1.0

jobs:
  include:
    - stage: deploy
      name: "Docs Upload"
      python: 3.6
      workspaces:
        use: docs
      if: |
        type != pull_request AND \
        (branch = master OR tag IS present)
      install:
        pip install doctr doctr-versions-menu
        pip install pyparsing --upgrade
      script:
        - |
          if [[ ! -z "$DOCTR_VERSIONS_MENU" ]]; then
              DOCTR_VERSIONS_COMMAND='--command "doctr-versions-menu"'
          fi
        - DEPLOY_DIR="${TRAVIS_TAG:=master}"
        - doctr deploy --build-tags $DEPLOY_DIR --deploy-branch-name gh-pages
          $DOCTR_VERSIONS_COMMAND 2>&1 > /tmp/doctr_deploy.txt
        - tail -n 10000 /tmp/doctr_deploy.txt
        - set +e
