jobs:
  include:
    - stage: test
      name: "Python Linter"
      install:
        - pip install flake8
      before_script:
        - cd "$TRAVIS_BUILD_DIR"
      script:
        - echo "$ flake8 $PYTHON_LINT_OPTIONS"
        - flake8 $PYTHON_LINT_OPTIONS
