jobs:
  include:
    - stage: build
      name: "Python - PIP"
      python: 3.9
      env: MPLBACKEND=agg
      install:
        - pip install --upgrade pip
        - echo "Req File':' ${REQUIREMENTS:=requirements.txt}"
        - echo "Dev Req File':' ${DEV_REQUIREMENTS:=dev-requirements.txt}"
        - echo "Pip packages installed for CI':' ${PIP_CI_PACKAGES:=pytest-cov}"
        - |
          # Install requirements
          if [[ ! -f "${REQUIREMENTS}" ]]; then
              echo "File not found: ${REQUIREMENTS}" 1>&2
              travis_terminate 1
          else
              pip install --requirement "${REQUIREMENTS}"
          fi
        - |
          # Install development requirements
          if [[ ! -f "${DEV_REQUIREMENTS}" ]]; then
              echo "File not found: ${DEV_REQUIREMENTS}" 1>&2
              travis_terminate 1
          else
              pip install --requirement "${DEV_REQUIREMENTS}"
          fi
        - |
          # Install Extras such as PyQt5
          if [[ ! -z "${PIP_EXTRAS}" ]]; then
              echo "Installing extra pip dependencies."
              pip install ${PIP_EXTRAS}
          fi
        - |
          # Install Extras such as PyQt5
          if [[ ! -z "${PIP_CI_PACKAGES}" ]]; then
              echo "Installing pip dependencies for CI."
              pip install ${PIP_CI_PACKAGES}
          fi
      script:
        - python -m pytest \
            --cov=. \
            --log-file="${AFTER_FAILURE_LOGFILE:-logs/run_tests_log.txt}" \
            --log-file-format='%(asctime)s.%(msecs)03d %(module)-15s %(levelname)-8s %(threadName)-10s %(message)s' \
            --log-file-date-format='%H:%M:%S' \
            --log-level=DEBUG
      after_failure:
        - LOGFILE="${AFTER_FAILURE_LOGFILE:-logs/run_tests_log.txt}"
        - |
          if [ -f "${LOGFILE}" ]; then
            cat "${LOGFILE}"
          else
            echo "Logfile ${LOGFILE} not found"
          fi
